version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "07:00"
  pull-request-branch-name:
    separator: "-"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: org.jetbrains:annotations
    versions:
    - "> 13.0"
  - dependency-name: org.eclipse.jetty:*
    versions:
    - ">= 12.0.0"
  - dependency-name: jakarta.servlet:jakarta.servlet-api
    versions:
    - ">= 6.0.0"
