package com.trib3.json.jackson

import com.fasterxml.jackson.core.Version
import com.fasterxml.jackson.core.util.VersionUtil
import com.fasterxml.jackson.databind.module.SimpleModule
import com.fasterxml.jackson.databind.ser.std.ToStringSerializer
import org.threeten.extra.YearQuarter
import java.util.Properties

/**
 * Jackson module for serializing and deserializing classes from [org.threeten.extra].
 *
 * Currently supports [YearQuarter] serialization for beans and [Map]s.
 */
class ThreeTenExtraModule : SimpleModule {
    companion object {
        // Read version number from the properties file generated by the build instead of hardcoding
        private val VERSION: Version

        init {
            val loader = this::class.java.classLoader
            val pkg = "com.trib3"
            val artifact = "json"
            VERSION = loader.getResourceAsStream("$pkg/$artifact.git.properties")?.use {
                val gitProps = Properties()
                gitProps.load(it)
                VersionUtil.parseVersion(gitProps.getProperty("git.build.version"), pkg, artifact)
            } ?: Version.unknownVersion()
        }
    }

    constructor() : super(VERSION) {
        addSerializer(YearQuarter::class.java, ToStringSerializer())
        addDeserializer(YearQuarter::class.java, YearQuarterDeserializer())
        addKeyDeserializer(YearQuarter::class.java, YearQuarterKeyDeserializer())
    }
}
