build:
  maxIssues: 0  # CHANGE FROM DEFAULT OF 10

complexity:
  LongParameterList:
    functionThreshold: 10 # CHANGE FROM DEFAULT OF 6
    constructorThreshold: 10 # CHANGE FROM DEFAULT OF 7
  TooManyFunctions:
    ignorePrivate: true # CHANGE FROM DEFAULT OF false

exceptions:
  TooGenericExceptionCaught:
    active: false  # CHANGE FROM DEFAULT OF true

performance:
  SpreadOperator:
    active: false # CHANGED FROM DEFAULT OF true

style:
  ForbiddenComment:
    active: false # CHANGE FROM DEFAULT OF true
  ForbiddenImport:
    active: true # CHANGE FROM DEFAULT OF false
    imports: 'com.google.inject.Inject,com.google.inject.name.Named,com.google.inject.Provider,com.google.inject.Singleton,com.google.inject.Scope' # CHANGE FROM DEFAULT OF ''
